---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata: 
  name: test-generator
  namespace: openshift-gitops
spec:
  generators:
    - merge:
        generators:
          - clusterDecisionResource:
              configMapRef: appset-placement
              name: test-placement
          - git:
              files:
                - path: 'cluster-definition/V4-{{clusterName}}/cluster.json'
              repoURL: 'https://github.com/mparram/clusterdecisionresource-demo.git'
              revision: main
        mergeKeys:
          - clusterName
          - cloud
  template:
    metadata:
      name: '{{name}}-test'
    spec:
      destination:
        server: '{{server}}'
      project: default
      source:
        path: 'aaaa/V4-{{cloud}}'
        repoURL: 'https://github.com/argoproj/argocd-example-apps/'
        targetRevision: HEAD
      syncPolicy: {}
