---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata: 
  name: test-generator
  namespace: openshift-gitops
spec:
  generators:
  - merge:
      mergeKeys:
        - server
        - cluster.gitopsname
      generators:
        - clusterDecisionResource:
            configMapRef: appset-placement
            name: test-placement
            requireAfterSeconds: 30
        - git:
            repoURL: https://github.com/mparram/clusterdecisionresource-demo.git
            revision: master
            files:
            - path: "cluster-definition/**/cluster.json"
  template:
    metadata:
      name: '{{name}}-test'
    spec:
      project: demo
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps/
        targetRevision: HEAD
        path: aaaa/{{cluster.name}}
      destination:
        server: '{{server}}'
      syncPolicy: {}
